apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: wnt-ns
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: dorrdorsela
               port:
                 number: 80
      host: dorrdorsela.com

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: minimal-ingress
#   namespace: wnt-ns
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: dorrdorsela.com
#     http:
#       paths:
#       - path: "/"
#         pathType: Prefix
#         backend:
#           service:
#             name: dorrdorsela
#             port:
#               number: 80

# apiVersion: networking.k8s.io/v1
# kind: Ingress 
# metadata:
#   name: ingress-controller
#   namespace: wnt-ns
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/rewrite-target: /

# spec:
  
#   rules:

#    - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nwtapp-service
#             port: 
#               number: 80