apiVersion: v1
kind: Service
metadata:
  name: dorrdorsela
  namespace: wnt-ns
  labels:
    app: dorrdorsela
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: dorrdorsela  

